#!/bin/bash

SYSTEM_IMAGE=/System/Library/PrivateFrameworks/WebCore.framework/missingImage.png 
CLEAR_IMAGE=/var/mobile/Library/SBSettings/Toggles/AdBlock/missingImage.png
if [ -f $SYSTEM_IMAGE ]; then
	mv $SYSTEM_IMAGE $CLEAR_IMAGE.orig
  cp $CLEAR_IMAGE $SYSTEM_IMAGE
fi

plutil -rmkey WebKitDNSPrefetchingEnabled /private/var/mobile/Library/Preferences/com.apple.mobilesafari.plist;

/bin/launchctl load -w /System/Library/LaunchDaemons/com.bigboss.sbsettingsd.plist
declare -a cydia
cydia=($CYDIA)

if [[ $1 == install ]]; then
    if [[ ${CYDIA+@} ]]; then
        eval "echo 'finish:restart' >&${cydia[0]}"
    fi
elif [[ $1 == upgrade ]]; then
    if [[ ${CYDIA+@} ]]; then
        eval "echo 'finish:restart' >&${cydia[0]}"
    fi
fi
exit 0
