#!/bin/bash
/bin/launchctl unload /System/Library/LaunchDaemons/com.bigboss.sbsettingsd.plist

rm /var/mobile/Library/SBSettings/Toggles/AdBlock/AdBlock.pid
cp /var/mobile/Library/SBSettings/Toggles/AdBlock/AdBlockOff_hosts /etc/hosts

SYSTEM_IMAGE=/System/Library/PrivateFrameworks/WebCore.framework/missingImage.png 
CLEAR_IMAGE=/var/mobile/Library/SBSettings/Toggles/AdBlock/missingImage.png
if [ -f $CLEAR_IMAGE.orig ]; then
	rm $SYSTEM_IMAGE
  mv $CLEAR_IMAGE.orig $SYSTEM_IMAGE
fi


declare -a cydia
cydia=($CYDIA)

if [[ $1 == remove ]]; then
    if [[ ${CYDIA+@} ]]; then
        eval "echo 'finish:restart' >&${cydia[0]}"
    fi
fi
exit 0
